// <auto-generated />
namespace Inspinia_MVC5_SeedProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_01));
        
        string IMigrationMetadata.Id
        {
            get { return "202201052017153_change_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
